[tools]
actionlint = "1.7.12"
ginkgo = '2.25.2'
golang = '1.26'
golangci-lint = "2.11.4"
"go:golang.org/x/tools/cmd/goimports" = "0.42.0"
'go:fybrik.io/crdoc' = "0.6.4"
helm = "4.1"
helm-ct = "3.14.0"
helm-docs = "1.14.2"
kube-controller-tools = { version = "0.20.1", exe = "controller-gen" }
kubectl = "1.35"
kustomize = "5.8.1"
pre-commit = "4.5.1"
setup-envtest = "0.23.3"
shellcheck = "0.11.0"
yamllint = "1.38.0"
yq = "4.52.5"

[settings]
experimental = true
