apiVersion: v1
kind: Secret
metadata:
  name: the-api-key-secret
type: Opaque
stringData:
  the-api-key: pnu_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
---
apiVersion: prefect.io/v1
kind: PrefectWorkPool
metadata:
  labels:
    app.kubernetes.io/name: prefect-operator
    app.kubernetes.io/managed-by: kustomize
  name: external-pool
spec:
  type: process
  server:
    remoteApiUrl: https://api.prefect.cloud
    accountId: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
    workspaceId: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
    apiKey:
      valueFrom:
        secretKeyRef:
          name: the-api-key-secret
          key: the-api-key
  workers: 3
