apiVersion: prefect.io/v1
kind: PrefectDeployment
metadata:
  name: prefectdeployment-minimal-sample
spec:
  server:
    name: "prefect-ephemeral"

  workPool:
    name: "process-work-pool"

  deployment:
    entrypoint: "flows/hello_world.py:hello"
