---
sources:
  common:
    kind: helmchart
    spec:
      url: https://charts.bitnami.com/bitnami
      name: common
      versionFilter:
        kind: semver
    sourceid: common
  prefect:
    name: Prefect GitHub releases
    kind: githubrelease
    spec:
      owner: PrefectHQ
      repository: prefect
      token: {{requiredEnv "GITHUB_TOKEN"}}
      versionFilter:
        kind: semver
    sourceid: prefect
conditions: {}
targets:
  operator:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: deploy/charts/prefect-operator/Chart.yaml
      key: $.dependencies[0].version
    sourceid: common
  prefect-version:
    name: update Prefect version constant
    kind: file
    spec:
      file: api/v1/versioning.go
      matchpattern: 'const DEFAULT_PREFECT_VERSION = "(.+)"'
      replacepattern: 'const DEFAULT_PREFECT_VERSION = "{{ source "prefect" }}"'
    sourceid: prefect
