{{ if .Values.kubeRbacProxy.create -}}
kind: ClusterRole
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ .Values.kubeRbacProxy.name }}
  labels:
    app.kubernetes.io/component: {{ .Values.kubeRbacProxy.name | quote }}
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs:
        - create
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs:
        - create
---
kind: ClusterRoleBinding
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ .Values.kubeRbacProxy.name | quote }}
  labels:
    app.kubernetes.io/component: {{ .Values.kubeRbacProxy.name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubeRbacProxy.name | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ template "operator.serviceAccountName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
{{- end }}