---
{{if .Values.kubeRbacProxy.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.kubeRbacProxy.name}}
  namespace: {{include "common.names.namespace" . | quote}}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4}}
    app.kubernetes.io/component: {{.Values.kubeRbacProxy.name}}
  {{- if .Values.commonAnnotations}}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4}}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: operator
{{- end -}}