{{ if .Values.kubeRbacProxy.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubeRbacProxy.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: {{ .Values.kubeRbacProxy.name }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/component: operator
{{- end }}