---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - prefect.io
  resources:
  - prefectautomations
  - prefectdeployments
  - prefectservers
  - prefectworkpools
  - prefectworkqueues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prefect.io
  resources:
  - prefectautomations/finalizers
  - prefectdeployments/finalizers
  - prefectservers/finalizers
  - prefectworkpools/finalizers
  - prefectworkqueues/finalizers
  verbs:
  - update
- apiGroups:
  - prefect.io
  resources:
  - prefectautomations/status
  - prefectdeployments/status
  - prefectservers/status
  - prefectworkpools/status
  - prefectworkqueues/status
  verbs:
  - get
  - patch
  - update
