name: Docker images

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docker-images.yaml
      - Dockerfile
      - .dockerignore
      - "src/**/*.py"
      - requirements.txt
      - requirements-dev.txt
      - pyproject.toml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  unit-tests:
    name: Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: PrefectHQ/prefect-operator:latest
          push: false
          pull: true
