---
# https://github.com/marketplace/actions/helm-unit-tests
name: Run Helm Unit Tests

"on":
  pull_request:
    branches:
      - main
    paths:
      - deploy/charts/**

permissions: {}

jobs:
  unittest:
    name: Run Helm Unit Tests
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
    steps:
      - uses: actions/checkout@v4
      # - uses: d3adb5/helm-unittest-action@v2
      #   with:
      #     helm-version: v3.15.3
