---
name: Updatecli dependency updates

"on":
  workflow_dispatch: {}
  schedule:
    # The first of each month at 10am EST
    - cron: 0 15 1 * *

permissions: {}

jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      # required to commit to a branch
      contents: write
      # required to open a pr with updatecli changes
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create branch for helm version updates
        run: |
          git checkout -b "helm-version-$DATE}"

      - name: Install updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Run updatecli in apply mode
        run: |
          updatecli apply --config .github/updatecli/manifest.yaml
          git commit -am "helm-version-$DATE}"
          git push --set-upstream origin "helm-version-$DATE}"

      - name: Install `helm-docs`
        uses: jdx/mise-action@v2
        with:
          install_args: helm-docs

      - name: Run helm-docs
        run: |
          helm-docs --template-files=README.md.gotmpl
          git commit -am "update readme"
          git push

      - name: Create pr
        run: |
          git checkout "helm-version-$DATE}"
          gh pr create --base main --title "helm-version-bump-$DATE}" --label dependencies
        env:
          GH_TOKEN: ${{ github.token }}
