---
name: Validate Updatecli Config

"on":
  pull_request:
    branches:
      - main
    paths:
      - .github/updatecli/**

permissions: {}

jobs:
  validate_updatecli_configs:
    name: Validate Updatecli Configs
    runs-on: ubuntu-latest
    permissions:
      # required to read from the repo
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install updatecli
        uses: updatecli/updatecli-action@v2

      - name: validate manifest
        run: updatecli diff --config .github/updatecli/manifest.yaml
